# Generated by Django 5.2.4 on 2025-07-24 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, help_text="e.g., 'Credit Card', 'PayPal'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_timestamp',
            field=models.DateTimeField(blank=True, help_text='Time payment was processed', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='unpaid', max_length=20),
        ),
    ]
